seed_everything: 42
trainer:
  precision: bf16-mixed
  max_epochs: 3
data:
  class_path: LightningIRDataModule
  init_args:
    num_workers: 4
    train_batch_size: 32
    train_dataset:
      class_path: RunDataset
      init_args:
        run_path_or_id: msmarco-passage/train/rank-distillm-rank-zephyr
        targets: rank
        depth: 100
        sample_size: 100
        sampling_strategy: top
model:
  class_path: CrossEncoderModule
  init_args:
    model_name_or_path: path-to-local-checkpoint
    # model_name_or_path: google/electra-base-discriminator
    # model_name_or_path: google/electra-large-discriminator
    config:
      class_path: CrossEncoderConfig
      init_args:
        query_length: 32
        doc_length: 256
    loss_functions:
      - class_path: RankNet
      # - class_path: ApproxRankMSE
      #   init_args:
      #     discount: log2
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.0e-05